---
- name: create user on all servers
  hosts: dbserver
  tasks:
    - name: user creation
      user:
        name: Anu
        password: intelliqit
        shell: /bin/bash
        uid: 1234
        home: /tmp/Anu
        comment: "A normal user"
...
