---
- name: Implementing error handling or expection handling
  hosts: all
  tasks:
    - block:
       - name: Install git on ubuntu using apt module
         apt:
           name: git
           state: present
           update_cache: yes
      rescue:
        - name: Install git on Redhat using yum module
          yum:
            name: git
            state: present
            update_cache: yes
      always:
        - name: Display success msg
          debug:
            msg: "Git installation succesfull"
